### PR TITLE
Add spacetiger

### PR DESCRIPTION
**Pull request by ysl-ee**
see PR in SpaceTiger repo (branch onboard) before merging!!

### CODE REVIEW

**Review by nicholaspad — CHANGES_REQUESTED** [review]
thanks for doing this! just a couple changes:

* add the "[NEW!]" prefix to SpaceTiger (see TigerMap for an example)
* can you make the screenshot have the same dimensions and/or ratio as all of the other images? otherwise the SpaceTiger screenshot size is inconsistent with the others:

CleanShot 2023-02-21 at 22 49 50@2x

@Danielpark1239 might be able to help with producing the screenshot since he did it for TigerMap

**Comment by ysl-ee** [comment]
@nicholaspad changes made!

**Review by nicholaspad — APPROVED** [review]
looks good :)

**Review by akelch11 — APPROVED** [review]

**Comment by nicholaspad** [comment]
@ysl-ee feel free to merge :)

**Pull request merged**
